version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./temp:/temp
    command: sh -c 'pytest --junitxml=/temp/testresults/test-results.xml --cov=junction --cov-report=xml:/temp/testresults/coverage.xml -v'
