# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_auto_20170610_1600'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='spamcomment',
            index_together=set([('comment', 'marked_by')]),
        ),
    ]
