# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-22 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_auto_20200321_0049'),
        ('proposals', '0025_auto_20200322_1904'),
    ]

    operations = [
    ]
