# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 06:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0027_auto_20200502_0540"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproposal",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproposalsectionreviewervote",
            name="history_change_reason",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproposal",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Primary Speaker",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproposal",
            name="proposal_section",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="proposals.ProposalSection",
                verbose_name="Proposal Section",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproposal",
            name="proposal_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="proposals.ProposalType",
                verbose_name="Proposal Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproposal",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Short 1-2 min video describing your talk",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Short 1-2 min video describing your talk",
            ),
        ),
    ]
