# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_auto_20170105_1713"),
        ("tickets", "0002_auto_20170104_0124"),
    ]

    operations = []
