# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_merge"),
        ("tickets", "0002_auto_20170404_2243"),
    ]

    operations = []
