name: Lint
on:
  push:
    branches-ignore:
      - django-2.2
  pull_request:
    branches-ignore:
      - django-2.2

jobs:
  lint:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install project dependencies
        run: |
          pip install --upgrade pip
          pip install nox
          pip install coveralls
      - name: Check for linting issues
        run: nox -s lint-3.8
